In [1]:
from pathlib import Path
from datetime import datetime
import pandas as pd

# File Load

In [14]:
dir = Path("./docs/")
fraud_path = dir.joinpath("fraud.csv")
ip_path = dir.joinpath("ip_country.xlsx")

#
fraud_file = pd.read_csv(fraud_path, index_col=0)
ip_file = pd.read_excel(ip_path)

#
fraud_file.head()

,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,ip_address,class
149671,285108,7/15/2015 4:36,9/10/2015 14:17,31,HZAKVUFTDOSFD,Direct,Chrome,M,49,2.818400e+09,0
15611,131009,1/24/2015 12:29,4/13/2015 4:53,31,XGQAJSOUJIZCC,SEO,IE,F,21,3.251268e+09,0
73178,328855,3/11/2015 0:54,4/5/2015 12:23,16,VCCTAYDCWKZIY,Direct,IE,M,26,2.727760e+09,0
84546,229053,1/7/2015 13:19,1/9/2015 10:12,29,MFFIHYNXCJLEY,SEO,Chrome,M,34,2.083420e+09,0
35978,108439,2/8/2015 21:11,4/9/2015 14:26,26,WMSXWGVPNIFBM,Ads,FireFox,M,33,3.207913e+09,0

In [5]:
def to_datetime(x):
    time_format = "%m/%d/%Y %H:%M"
    return datetime.strptime(x, time_format)

In [6]:
fraud_file["signup_time"] = fraud_file["signup_time"].apply(to_datetime)
fraud_file["purchase_time"] = fraud_file["purchase_time"].apply(to_datetime)

In [7]:
fraud_file

,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,ip_address,class
149671,285108,2015-07-15 04:36:00,2015-09-10 14:17:00,31,HZAKVUFTDOSFD,Direct,Chrome,M,49,2.818400e+09,0
15611,131009,2015-01-24 12:29:00,2015-04-13 04:53:00,31,XGQAJSOUJIZCC,SEO,IE,F,21,3.251268e+09,0
73178,328855,2015-03-11 00:54:00,2015-04-05 12:23:00,16,VCCTAYDCWKZIY,Direct,IE,M,26,2.727760e+09,0
84546,229053,2015-01-07 13:19:00,2015-01-09 10:12:00,29,MFFIHYNXCJLEY,SEO,Chrome,M,34,2.083420e+09,0
35978,108439,2015-02-08 21:11:00,2015-04-09 14:26:00,26,WMSXWGVPNIFBM,Ads,FireFox,M,33,3.207913e+09,0
...,...,...,...,...,...,...,...,...,...,...,...
13862,116698,2015-02-26 11:51:00,2015-04-16 22:57:00,46,UJYRDGZXTFFJG,Ads,Chrome,M,18,2.509395e+09,0
122655,122699,2015-08-01 18:40:00,2015-08-25 07:56:00,26,EMMTCPTUYQYPX,Ads,IE,F,36,2.946612e+09,0
125965,115120,2015-07-25 12:50:00,2015-09-03 04:10:00,41,YSZGGEARGETEU,SEO,Chrome,M,31,5.570629e+08,0
31108,87098,2015-04-02 21:11:00,2015-06-22 16:51:00,50,BJDWRJULJZNOV,SEO,Chrome,F,43,2.687887e+09,0
46646,341401,2015-07-15 15:11:00,2015-09-03 13:45:00,32,AOKZUNMPCDKVK,Ads,Chrome,F,47,1.174840e+09,0

In [8]:
fraud_file.insert(loc=3, column="time_delta", value=None)

In [9]:
fraud_file["time_delta"] = fraud_file["purchase_time"] - fraud_file["signup_time"]

In [10]:
fraud_file["time_delta"].iloc[0].total_seconds() / 60

82661.0

In [11]:
def to_minuets(x):
    return x.total_seconds() / 60

In [12]:
fraud_file["time_delta"] = fraud_file["time_delta"].apply(to_minuets)

In [13]:
fraud_file

,user_id,signup_time,purchase_time,time_delta,purchase_value,device_id,source,browser,sex,age,ip_address,class
149671,285108,2015-07-15 04:36:00,2015-09-10 14:17:00,82661.0,31,HZAKVUFTDOSFD,Direct,Chrome,M,49,2.818400e+09,0
15611,131009,2015-01-24 12:29:00,2015-04-13 04:53:00,113304.0,31,XGQAJSOUJIZCC,SEO,IE,F,21,3.251268e+09,0
73178,328855,2015-03-11 00:54:00,2015-04-05 12:23:00,36689.0,16,VCCTAYDCWKZIY,Direct,IE,M,26,2.727760e+09,0
84546,229053,2015-01-07 13:19:00,2015-01-09 10:12:00,2693.0,29,MFFIHYNXCJLEY,SEO,Chrome,M,34,2.083420e+09,0
35978,108439,2015-02-08 21:11:00,2015-04-09 14:26:00,85995.0,26,WMSXWGVPNIFBM,Ads,FireFox,M,33,3.207913e+09,0
...,...,...,...,...,...,...,...,...,...,...,...,...
13862,116698,2015-02-26 11:51:00,2015-04-16 22:57:00,71226.0,46,UJYRDGZXTFFJG,Ads,Chrome,M,18,2.509395e+09,0
122655,122699,2015-08-01 18:40:00,2015-08-25 07:56:00,33916.0,26,EMMTCPTUYQYPX,Ads,IE,F,36,2.946612e+09,0
125965,115120,2015-07-25 12:50:00,2015-09-03 04:10:00,57080.0,41,YSZGGEARGETEU,SEO,Chrome,M,31,5.570629e+08,0
31108,87098,2015-04-02 21:11:00,2015-06-22 16:51:00,116380.0,50,BJDWRJULJZNOV,SEO,Chrome,F,43,2.687887e+09,0
46646,341401,2015-07-15 15:11:00,2015-09-03 13:45:00,71914.0,32,AOKZUNMPCDKVK,Ads,Chrome,F,47,1.174840e+09,0

In [13]:
fraud = fraud_file[fraud_file["class"] == 1]
non_fraud = fraud_file[fraud_file["class"] == 0]

KeyError: 'class'

In [53]:
fraud.head()

,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,ip_address,class
68779,264899,1/12/2015 11:43,1/12/2015 11:43,57,RGNKMWSCHLGFL,Direct,Chrome,M,32,1.288372e+09,1
118822,41373,1/6/2015 13:42,1/6/2015 13:42,56,BYSNUKLSWIKBD,SEO,Chrome,M,27,1.239228e+09,1
147030,343842,3/12/2015 18:37,3/14/2015 22:54,34,ISUILVGRBBMYZ,Ads,Safari,F,33,7.166723e+08,1
27845,37810,1/6/2015 14:23,1/6/2015 14:23,60,HLGDGXZBJPJYZ,SEO,Chrome,M,58,1.969298e+09,1
132134,238906,1/7/2015 21:49,2/15/2015 17:29,61,OYUCSCPRHJDKG,Ads,Safari,F,38,4.019587e+09,1

In [54]:
non_fraud.head()

,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,ip_address,class
149671,285108,7/15/2015 4:36,9/10/2015 14:17,31,HZAKVUFTDOSFD,Direct,Chrome,M,49,2.818400e+09,0
15611,131009,1/24/2015 12:29,4/13/2015 4:53,31,XGQAJSOUJIZCC,SEO,IE,F,21,3.251268e+09,0
73178,328855,3/11/2015 0:54,4/5/2015 12:23,16,VCCTAYDCWKZIY,Direct,IE,M,26,2.727760e+09,0
84546,229053,1/7/2015 13:19,1/9/2015 10:12,29,MFFIHYNXCJLEY,SEO,Chrome,M,34,2.083420e+09,0
35978,108439,2/8/2015 21:11,4/9/2015 14:26,26,WMSXWGVPNIFBM,Ads,FireFox,M,33,3.207913e+09,0